// Feature: roza-step4-avatar-video, Property 10: Meet and stream presence routing with fault isolation
//
// Validates: Requirements 6.6, 7.1, 9.3, 9.4
//
// Property 10 drives the Avatar_Connector I/O shell (`createAvatarConnector`)
// with in-memory fake `MeetSession`/`StreamSession` implementations whose
// outcome (resolve OR throw) is generated by fast-check, and asserts two
// guarantees hold for EVERY generated outcome:
//
//   1. PRESENCE ROUTING (Req 7.1) — when the avatar + the relevant
//      sub-capability are enabled (and, for Meet, consent + Meet_Credentials are
//      present), `joinMeet` delegates to `meet.join` with the untrusted URL and
//      the configured `Meet_Credentials`, and `startStream` delegates to
//      `stream.start` with the configured `RTMP_Target` `{ url, key }` and the
//      combined `AvatarStream` (the configured video format paired with the
//      avatar PCM audio format).
//
//   2. FAULT ISOLATION (Req 6.6, 9.3, 9.4) — when the injected session FAILS /
//      throws, the connector LOGS the failure, RELEASES that session's resources
//      (its `avatar_sessions` audit row is closed), and returns `{ ok: false }`
//      WITHOUT throwing. `joinMeet` / `startStream` never reject: the call
//      resolves and the service is not crashed, so the `internal` / `telegram` /
//      `email` / `voice` channels keep running.
//
// No real browser, RTMP endpoint, GPU, or kernel module runs — every external
// edge is an in-memory fake (Req 12.5).

import { describe, it, expect } from 'vitest';
import fc from 'fast-check';

import { createAvatarConnector } from './avatarConnector.js';
import type { AvatarRenderer } from './renderer.js';
import type { VirtualCamera } from './virtualCamera.js';
import type { VirtualMicrophone } from './virtualMicrophone.js';
import type { MeetSession, MeetCredentials } from './meetSession.js';
import type { StreamSession, StreamTarget } from './streamSession.js';
import type { AvatarStream } from './avatarFormat.js';
import { TELEPHONY_PCM_16K, type AudioFormat } from '../voice/audio.js';
import type { Logger } from '../../types.js';
import type {
  AvatarOutcome,
  AvatarSession,
  AvatarSessionKind,
  Repository,
} from '../../repository.js';
import type { RozaConfig, AvatarChannelConfig, AvatarPixelFormat } from '../../config.js';

/** Minimum fast-check iterations mandated by the design for every property. */
const NUM_RUNS = 100;

/** Deterministic audit timestamp so the test never reads a real clock. */
const FIXED_NOW = new Date('2024-01-01T00:00:00.000Z');

/** The generated outcome of an injected presence session. */
type SessionMode = 'success' | 'throw';

const sessionModeArb: fc.Arbitrary<SessionMode> = fc.constantFrom(
  'success' as const,
  'throw' as const,
);

const pixelFormatArb: fc.Arbitrary<AvatarPixelFormat> = fc.constantFrom(
  'rgba' as const,
  'yuv420p' as const,
  'nv12' as const,
);

/** A non-blank string (so the consent/credentials/target gates pass). */
const nonBlankArb: fc.Arbitrary<string> = fc
  .string({ minLength: 1, maxLength: 40 })
  .filter((s) => s.trim().length > 0);

// ───────────────────────────────────────────────────────────────────────────
// Fakes — every external edge is in-memory, recording what it was handed.
// ───────────────────────────────────────────────────────────────────────────

/** A captured `meet.join` delegation. */
interface MeetJoinCall {
  meetUrl: string;
  creds: MeetCredentials;
}

/** Build a fake `MeetSession` that records `join` calls and resolves/throws by mode. */
function makeFakeMeet(mode: SessionMode): { session: MeetSession; joinCalls: MeetJoinCall[] } {
  const joinCalls: MeetJoinCall[] = [];
  const session: MeetSession = {
    descriptor: { backend: 'playwright', license: 'Apache-2.0' },
    async join(meetUrl: string, creds: MeetCredentials): Promise<void> {
      joinCalls.push({ meetUrl, creds: { ...creds } });
      if (mode === 'throw') {
        throw new Error('fake meet join failure');
      }
    },
    async mute(): Promise<void> {},
    async leave(): Promise<void> {},
  };
  return { session, joinCalls };
}

/** A captured `stream.start` delegation. */
interface StreamStartCall {
  target: StreamTarget;
  stream: AvatarStream;
}

/** Build a fake `StreamSession` that records `start` calls and resolves/throws by mode. */
function makeFakeStream(mode: SessionMode): {
  session: StreamSession;
  startCalls: StreamStartCall[];
} {
  const startCalls: StreamStartCall[] = [];
  const session: StreamSession = {
    descriptor: { backend: 'ffmpeg', license: 'GPL-2.0' },
    async start(target: StreamTarget, stream: AvatarStream): Promise<void> {
      startCalls.push({ target: { ...target }, stream });
      if (mode === 'throw') {
        throw new Error('fake stream start failure');
      }
    },
    async stop(): Promise<void> {},
  };
  return { session, startCalls };
}

/** A recorded `avatar_sessions` audit row (start + optional close). */
interface AuditRecord {
  id: string;
  kind: AvatarSessionKind;
  target: string | null;
  closed: { outcome: AvatarOutcome; at: string } | null;
}

/** Build a fake `Repository` recording only the avatar-session audit calls. */
function makeFakeRepo(): { repo: Repository; records: AuditRecord[] } {
  const records: AuditRecord[] = [];
  let counter = 0;
  const repo = {
    startAvatarSession(kind: AvatarSessionKind, target?: string | null): AvatarSession {
      const id = `audit-${counter++}`;
      records.push({ id, kind, target: target ?? null, closed: null });
      return {
        id,
        kind,
        target: target ?? null,
        outcome: 'in_progress',
        started_at: FIXED_NOW.toISOString(),
        ended_at: null,
      };
    },
    endAvatarSession(id: string, outcome: AvatarOutcome, at: string): void {
      const rec = records.find((r) => r.id === id);
      if (rec) {
        rec.closed = { outcome, at };
      }
    },
  } as unknown as Repository;
  return { repo, records };
}

/** A captured log line. */
interface LogLine {
  level: 'info' | 'error';
  message: string;
  meta: Record<string, unknown> | undefined;
}

/** Build a spy `Logger` capturing every info/error line. */
function makeSpyLogger(): { logger: Logger; lines: LogLine[] } {
  const lines: LogLine[] = [];
  const logger: Logger = {
    info(message: string, meta?: Record<string, unknown>): void {
      lines.push({ level: 'info', message, meta });
    },
    error(message: string, meta?: Record<string, unknown>): void {
      lines.push({ level: 'error', message, meta });
    },
  };
  return { logger, lines };
}

/** Inert renderer/camera/microphone — the Meet/stream paths never touch them. */
const inertRenderer: AvatarRenderer = {
  descriptor: { engine: 'fake', license: 'MIT' },
  async render() {
    throw new Error('renderer not exercised by presence routing');
  },
};
const inertCamera: VirtualCamera = {
  descriptor: { device: 'fake-cam', backend: 'fake', license: 'MIT' },
  async open() {},
  async write() {},
  async close() {},
};
const inertMicrophone: VirtualMicrophone = {
  descriptor: { device: 'fake-mic', backend: 'fake', license: 'MIT' },
  async open() {},
  async write() {},
  async close() {},
};

/** Generated, fully-enabled avatar config (meet + stream operative). */
interface EnabledAvatarInputs {
  width: number;
  height: number;
  fps: number;
  pixelFormat: AvatarPixelFormat;
  account: string;
  password: string;
  streamUrl: string;
  streamKey: string;
}

const enabledAvatarArb: fc.Arbitrary<EnabledAvatarInputs> = fc.record({
  width: fc.integer({ min: 1, max: 1920 }),
  height: fc.integer({ min: 1, max: 1080 }),
  fps: fc.integer({ min: 1, max: 60 }),
  pixelFormat: pixelFormatArb,
  account: nonBlankArb,
  password: nonBlankArb,
  streamUrl: nonBlankArb,
  streamKey: nonBlankArb,
});

/** Build an enabled `AvatarChannelConfig` from generated inputs. */
function makeAvatarConfig(a: EnabledAvatarInputs): AvatarChannelConfig {
  return {
    enabled: true,
    video: { width: a.width, height: a.height, fps: a.fps, pixelFormat: a.pixelFormat },
    latency: { renderMs: 4000 },
    renderer: { endpoint: 'http://renderer.local', engine: 'fake' },
    devices: { camera: 'cam0', microphone: 'mic0' },
    meet: { enabled: true, consent: true, account: a.account, password: a.password },
    stream: { enabled: true, url: a.streamUrl, key: a.streamKey },
  };
}

/** Build a fully-resolved RozaConfig with the supplied enabled avatar config. */
function makeConfig(avatar: AvatarChannelConfig): RozaConfig {
  return {
    rozaPrivateKey: 'test-private-key',
    openRouterApiKey: 'test-api-key',
    openRouterModel: 'openai/gpt-4o-mini',
    dataDir: '/tmp/roza-test',
    timezone: 'Africa/Kinshasa',
    activeWindow: { startMinutes: 420, endMinutes: 1320 },
    keyVersion: 'v1',
    telegram: { enabled: false, botToken: '', allowlist: [] },
    mail: {
      enabled: false,
      imap: { host: '', port: 0, user: '', password: '' },
      smtp: { host: '', port: 0, user: '', password: '' },
      allowlist: [],
    },
    voice: {
      enabled: false,
      sip: { host: '', port: 0, user: '', password: '', realm: '' },
      allowlist: [],
      defaultAccess: 'reject',
      quietHoursInbound: 'take_message',
      tts: { engine: 'piper', voice: 'en_US-amy-medium', model: 'en_US-amy-medium' },
      stt: { engine: 'whisper.cpp', model: 'ggml-base.en' },
      maxReplyChars: 1000,
      latency: { ttsMs: 5000, sttMs: 5000, endToEndMs: 8000, ringTimeoutMs: 30000 },
    },
    avatar,
  };
}

describe('Meet and stream presence routing with fault isolation (Property 10)', () => {
  // Feature: roza-step4-avatar-video, Property 10: Meet and stream presence routing with fault isolation
  // Validates: Requirements 6.6, 7.1, 9.3, 9.4
  it('joinMeet delegates with URL + credentials, and isolates a failing session without throwing', async () => {
    await fc.assert(
      fc.asyncProperty(
        enabledAvatarArb,
        nonBlankArb,
        sessionModeArb,
        async (avatarInputs, meetUrl, mode) => {
          const avatar = makeAvatarConfig(avatarInputs);
          const cfg = makeConfig(avatar);
          const { session: meet, joinCalls } = makeFakeMeet(mode);
          const { repo, records } = makeFakeRepo();
          const { logger, lines } = makeSpyLogger();

          const connector = createAvatarConnector({
            renderer: inertRenderer,
            camera: inertCamera,
            microphone: inertMicrophone,
            meet,
            cfg,
            avatarImage: () => new Uint8Array(0),
            now: () => FIXED_NOW,
            logger,
            audioOnlyDeliver: async () => {},
            repo,
          });

          // The call MUST resolve for any session outcome — never reject
          // (fault isolation: the service is not crashed). Req 6.6, 9.3.
          const result = await connector.joinMeet(meetUrl);

          // ENABLED join always delegates to meet.join with the untrusted URL
          // and the configured Meet_Credentials (Req 7.1) — for both outcomes.
          expect(joinCalls).toHaveLength(1);
          expect(joinCalls[0]?.meetUrl).toBe(meetUrl);
          expect(joinCalls[0]?.creds).toEqual({
            account: avatar.meet.account,
            password: avatar.meet.password,
          });

          // An audit row was opened for the appearance with the URL as target
          // (never a credential).
          const meetAudits = records.filter((r) => r.kind === 'meet');
          expect(meetAudits).toHaveLength(1);
          expect(meetAudits[0]?.target).toBe(meetUrl);

          if (mode === 'success') {
            expect(result.ok).toBe(true);
          } else {
            // FAULT ISOLATION (Req 6.6, 9.3): log the failure, release the
            // session's resources (audit closed 'failed'), return { ok:false }.
            expect(result.ok).toBe(false);
            expect(lines.some((l) => l.level === 'error' && l.message === 'avatar.meet.join_failed')).toBe(
              true,
            );
            expect(meetAudits[0]?.closed).toEqual({ outcome: 'failed', at: FIXED_NOW.toISOString() });

            // The connector is not crashed — a follow-up control call also resolves.
            await expect(connector.leaveMeet()).resolves.toBeUndefined();
          }
        },
      ),
      { numRuns: NUM_RUNS },
    );
  });

  // Feature: roza-step4-avatar-video, Property 10: Meet and stream presence routing with fault isolation
  // Validates: Requirements 6.6, 7.1, 9.3, 9.4
  it('startStream delegates with target + combined AvatarStream, and isolates a failing session without throwing', async () => {
    /** The avatar PCM audio format the connector pairs into the combined stream. */
    const expectedAudio: AudioFormat = TELEPHONY_PCM_16K;

    await fc.assert(
      fc.asyncProperty(enabledAvatarArb, sessionModeArb, async (avatarInputs, mode) => {
        const avatar = makeAvatarConfig(avatarInputs);
        const cfg = makeConfig(avatar);
        const { session: stream, startCalls } = makeFakeStream(mode);
        const { repo, records } = makeFakeRepo();
        const { logger, lines } = makeSpyLogger();

        const connector = createAvatarConnector({
          renderer: inertRenderer,
          camera: inertCamera,
          microphone: inertMicrophone,
          stream,
          cfg,
          avatarImage: () => new Uint8Array(0),
          now: () => FIXED_NOW,
          logger,
          audioOnlyDeliver: async () => {},
          repo,
        });

        // The call MUST resolve for any session outcome — never reject
        // (fault isolation: the service is not crashed). Req 9.4.
        const result = await connector.startStream();

        // ENABLED startStream always delegates to stream.start with the
        // configured RTMP_Target { url, key } and the combined AvatarStream
        // (configured video format paired with the avatar PCM audio) — Req 7.1.
        expect(startCalls).toHaveLength(1);
        expect(startCalls[0]?.target).toEqual({ url: avatar.stream.url, key: avatar.stream.key });
        expect(startCalls[0]?.stream.video).toEqual(avatar.video);
        expect(startCalls[0]?.stream.audio).toEqual(expectedAudio);

        // An audit row was opened with the RTMP ingest URL as target (never the key).
        const streamAudits = records.filter((r) => r.kind === 'stream');
        expect(streamAudits).toHaveLength(1);
        expect(streamAudits[0]?.target).toBe(avatar.stream.url);

        if (mode === 'success') {
          expect(result.ok).toBe(true);
        } else {
          // FAULT ISOLATION (Req 9.4): log the failure, release the session's
          // resources (audit closed 'failed'), return { ok:false }.
          expect(result.ok).toBe(false);
          expect(
            lines.some((l) => l.level === 'error' && l.message === 'avatar.stream.start_failed'),
          ).toBe(true);
          expect(streamAudits[0]?.closed).toEqual({ outcome: 'failed', at: FIXED_NOW.toISOString() });

          // The connector is not crashed — a follow-up control call also resolves.
          await expect(connector.stopStream()).resolves.toBeUndefined();
        }
      }),
      { numRuns: NUM_RUNS },
    );
  });
});
